### ISSUE TITLE
Some errors occur where music is cut off

### ISSUE THREAD

**Issue by lia656** [neon0313/Kkangtong#3]
해당의 위와 같은 음악 끊김 문제가 발생합니다, 본 경우가 매우 가끔 일어납니다

**Comment by neon0313** [comment]
> 해당의 위와 같은 음악 끊김 문제가 발생합니다, 본 경우가 매우 가끔 일어납니다

본 경우 디스코드 패킷이나 디스코드 서버 문제일 수 있습니다.

**Comment by neon0313** [comment]
본 경우 디스코드 서버 내에 지역을 `홍콩`이나 `일본` 쪽으로 변경해주시기 바랍니다.

**Comment by lia656** [comment]
감사합니다.
